### ISSUE TITLE
Crash on file open

### ISSUE THREAD

**Issue by lapo-luchini** [Nutomic/syncthing-lite#13]
```
01-15 12:18:12.930 23172 23907 I DownloadFileTask: downloaded file = personal/Images/IMG_20171228_111545.jpg
--------- beginning of crash
01-15 12:18:12.945 23172 23907 E AndroidRuntime: FATAL EXCEPTION: Thread-5
01-15 12:18:12.945 23172 23907 E AndroidRuntime: Process: net.syncthing.lite, PID: 23172
01-15 12:18:12.945 23172 23907 E AndroidRuntime: android.os.FileUriExposedException: file:///storage/emulated/0/Download/IMG_20171228_111545.jpg exposed beyond app through Intent.getData()
01-15 12:18:12.945 23172 23907 E AndroidRuntime:        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1796)
01-15 12:18:12.945 23172 23907 E AndroidRuntime:        at android.net.Uri.checkFileUriExposed(Uri.java:2346)
01-15 12:18:12.945 23172 23907 E AndroidRuntime:        at android.content.Intent.prepareToLeaveProcess(Intent.java:8983)
01-15 12:18:12.945 23172 23907 E AndroidRuntime:        at android.content.Intent.prepareToLeaveProcess(Intent.java:8942)
01-15 12:18:12.945 23172 23907 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
01-15 12:18:12.945 23172 23907 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4402)
01-15 12:18:12.945 23172 23907 E AndroidRuntime:        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
01-15 12:18:12.945 23172 23907 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
01-15 12:18:12.945 23172 23907 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4360)
01-15 12:18:12.945 23172 23907 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:732)
```

**Comment by lapo-luchini** [comment]
Might be related to bug #1 ?
[Documentation](https://developer.android.com/reference/android/os/FileUriExposedException.html) strongly discourages the usage of `file://` (even in temp) and use `content://` instead.
