### ISSUE TITLE
Sometimes download get stuck

### ISSUE THREAD

**Issue by lapo-luchini** [Nutomic/syncthing-lite#30]
Downloading a very small file (12KiB) always succeeds.
Download a bigger one (~1MiB), it often get stuck at 50% or 90%.
I didn't extract `logcat` yet.

**Comment by lapo-luchini** [comment]
I checked `logcat`, the first document (100%) and the second one (stuck at 69.2%) don't show anything much different from one another.

**Comment by Nutomic** [comment]
Yes I've noticed that myself. Some bug in the download logic (which is rather complicated).

**Comment by Pazuu** [comment]
As of version 0.3.1 i cannot reproduce this issue :smile_cat:

**Comment by Nutomic** [comment]
@lapo-luchini Is it working now for you?

**Comment by lapo-luchini** [comment]
Seems to be working, from home Wi-Fi (where one node is located).
Let me try with mobile connection too.

**Comment by lapo-luchini** [comment]
No, it still happens both in 4G and, after having returned to Wi-Fi, there too. :(
Or rather, it doesn't get stuck, it immediately produces a bubble notification with «Impossibile scaricare il file» (impossible to download the file).

**Comment by lapo-luchini** [comment]
Seems to be this:
```
12-07 10:52:18.129  4844  4990 W net.syncthing.a.a.a.h: failed to connect to DeviceAddress(deviceId=DeviceId(deviceId=AV5Y2W2-…-6NSJXAP), instanceId=null, address=tcp://176.9.71.213:22000, producer=UNKNOWN, score=54, lastModified=Fri Dec 07 10:48:15 GMT+01:00 2018)
12-07 10:52:18.129  4844  4990 W net.syncthing.a.a.a.h: java.io.EOFException
12-07 10:52:18.129  4844  4990 W net.syncthing.a.a.a.h:  at java.io.DataInputStream.readFully(DataInputStream.java:200)
12-07 10:52:18.129  4844  4990 W net.syncthing.a.a.a.h:  at java.io.DataInputStream.readShort(DataInputStream.java:317)
12-07 10:52:18.129  4844  4990 W net.syncthing.a.a.a.h:  at net.syncthing.a.a.a.p.a(PostAuthenticationMessageHandler.kt:98)
```
After a while, Wi-Fi began working again.

**Comment by lapo-luchini** [comment]
I read [here](https://github.com/syncthing/syncthing-lite/issues/6#issuecomment-421540043) that syncthing/syncthing-java#10 has not yet landed, is that still true?
This might be only that.
