### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by jdevora** [Nutomic/syncthing-lite#5]
I tried the App in a Sony Z5 with Android 7.7.1 installed and crashes a few seconds after showing the initial screen.

Those are the logs I pulled with logcat
```
12-22 12:57:04.398 17593 17608 I LibConnectionHandler: storage space = dir / used space / free space
12-22 12:57:04.398 17593 17608 I LibConnectionHandler: 	cache = /storage/emulated/0/Android/data/net.syncthing.lite/cache/cache 0 bytes / 1 GB
12-22 12:57:04.398 17593 17608 I LibConnectionHandler: 	temp = /data/user/0/net.syncthing.lite/cache/a_sync_client_temp 0 bytes / 1 GB
12-22 12:57:04.398 17593 17608 I LibConnectionHandler: 	database = /storage/emulated/0/Android/data/net.syncthing.lite/files/database 60 KB / 1 GB
12-22 12:57:04.401 17593 17608 I SqlRepository: starting sql database
12-22 12:57:04.430 17593 17608 I HikariDataSource: HikariPool-1 - Started.
12-22 12:57:04.436 17593 17608 W art     : Before Android 4.1, method double java.util.concurrent.ThreadLocalRandom.internalNextDouble(double, double) would have incorrectly overridden the package-private method in java.util.Random
12-22 12:57:04.436 17593 17608 W art     : Before Android 4.1, method int java.util.concurrent.ThreadLocalRandom.internalNextInt(int, int) would have incorrectly overridden the package-private method in java.util.Random
12-22 12:57:04.436 17593 17608 W art     : Before Android 4.1, method long java.util.concurrent.ThreadLocalRandom.internalNextLong(long, long) would have incorrectly overridden the package-private method in java.util.Random
12-22 12:57:04.567 17593 17608 I c*.z*.h*.p*.PoolBase: HikariPool-1 - Driver does not support get/set network timeout for connections. (No interface method getNetworkTimeout()I in class Ljava/sql/Connection; or its super classes (declaration of 'java.sql.Connection' appears in /system/framework/core-oj.jar))
12-22 12:57:04.651 17593 17608 I SqlRepository: database check ok, version = 13
12-22 12:57:04.657 17593 17608 I SqlRepository: recreateTemporaryTables BEGIN
12-22 12:57:04.659 17593 17608 I SqlRepository: recreateTemporaryTables END
12-22 12:57:04.660 17593 17608 I DiscoveryHandler: init
12-22 12:57:04.685  2125  2423 I InputDispatcher: Focus entered window: Window{bbcdc92 u0 net.syncthing.lite/net.syncthing.lite.activities.MainActivity}
12-22 12:57:04.693 17593 17593 D AndroidRuntime: Shutting down VM
--------- beginning of crash
12-22 12:57:04.694 17593 17593 E AndroidRuntime: FATAL EXCEPTION: main
12-22 12:57:04.694 17593 17593 E AndroidRuntime: Process: net.syncthing.lite, PID: 17593
12-22 12:57:04.694 17593 17593 E AndroidRuntime: kotlin.KotlinNullPointerException
12-22 12:57:04.694 17593 17593 E AndroidRuntime: 	at net.syncthing.lite.activities.SyncthingActivity$InitTask.onPostExecute(SyncthingActivity.kt:99)
12-22 12:57:04.694 17593 17593 E AndroidRuntime: 	at net.syncthing.lite.activities.SyncthingActivity$InitTask.onPostExecute(SyncthingActivity.kt:59)
12-22 12:57:04.694 17593 17593 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:667)
12-22 12:57:04.694 17593 17593 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
12-22 12:57:04.694 17593 17593 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
12-22 12:57:04.694 17593 17593 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-22 12:57:04.694 17593 17593 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
12-22 12:57:04.694 17593 17593 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6274)
12-22 12:57:04.694 17593 17593 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-22 12:57:04.694 17593 17593 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
12-22 12:57:04.694 17593 17593 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
12-22 12:57:04.696  2125  5923 D ActivityManager: New dropbox entry: net.syncthing.lite, data_app_crash, a224a7aa-4fa1-46e7-9051-4795754b2c11
12-22 12:57:04.697  2125  5923 W ActivityManager:   Force finishing activity net.syncthing.lite/.activities.MainActivity
12-22 12:57:04.703  2125  5923 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
12-22 12:57:04.722  2125  2125 I BroadcastQueue: am_broadcast_enqueue: [background,1,Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) },4]
12-22 12:57:04.724   694   694 D clmlib  : Got activities:0x00000008
12-22 12:57:04.724   694   694 I JavaDumper:JavaDumperThread: addEvent: data_app_crash@1513947424720.txt processName: net.syncthing.lite
12-22 12:57:04.724   694   824 I JavaDumper:JavaDumperThread: Event: data_app_crash@1513947424720.txt TimeStamp: 1513947424
12-22 12:57:04.730  2125  2156 I InputDispatcher: Focus entered window: Window{39b82fd u0 Application Error: net.syncthing.lite}
```

**Comment by Nutomic** [comment]
Oops, I should have checked to make sure the initial start works.
