### ISSUE TITLE
BlockPusher is broken/ file uploading does not work

### ISSUE THREAD

**Issue by l-jonas** [Nutomic/syncthing-lite#70]
Problem: BlockPusher.DataSource closes the inputstream during the constructer with ``use`` but tries to read the blocks later from it

**Comment by vext01** [comment]
I'm not sure if this is the same issue, but I'm unable to upload files too.

It either:
 * Crashes the app, restarting it, or
 * Get's stuck at 0%.

**Comment by vext01** [comment]
Here's the log:
```
java.io.IOException: Stream Closed
 at java.io.FileInputStream.read(FileInputStream.java:300)
 at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:942)
 at org.a.a.b.b.a(IOUtils.java:2909)
 at org.a.a.b.b.b(IOUtils.java:3015)
 at org.a.a.b.b.a(IOUtils.java:3035)
 at net.syncthing.a.a.e$b.a(BlockPusher.kt:277)
 at net.syncthing.a.a.e$f$1.c_(BlockPusher.kt:92)
 at a.c.b.a.a.b(ContinuationImpl.kt:32)
 at kotlinx.coroutines.az$a.a(Dispatched.kt:235)
 at kotlinx.coroutines.aw.run(Dispatched.kt:81)
 at kotlinx.coroutines.c.i.run(Tasks.kt:94)
 at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:586)
 at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:60)
 at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:732)
```

Is this project still active?

**Comment by l-jonas** [comment]
@vext01 

> Is this project still active?

I am not satisfied with the communication with the Syncthing project and due to that I don't continue the development of Syncthing Lite.

**Comment by vext01** [comment]
I see.

That's a real shame, as I think your project could be very useful.

Thanks for the reply, anyway.

**Comment by Pazuu** [comment]
> @vext01
> 
> > Is this project still active?
> 
> I am not satisfied with the communication with the Syncthing project and due to that I don't continue the development of Syncthing Lite.

I am sorry to hear that! But thank you for all your work!!
