### ISSUE TITLE
Crash when adding device via QR Codes

### ISSUE THREAD

**Issue by napseis** [Nutomic/syncthing-lite#8]
hi,
When I want to add a device, via QR code scanning, the app crash after the scan.
I run on latest version of Resurection Remix OS on a OnePlus One. I have otherwise a syncthing app (which was not running when i tried the lite), which works fine.

I'll be happy to help provide more informations (logs somewhere ?)

On a side note, if i understood correctly the capabilities of this app, i can delete a file on my phone but retain it on the "server" ?

Thanks

**Comment by Nutomic** [comment]
You can use an app like "aLogCat" to get the crash log.

If you download a file and then delete it from the downloads folder, it will still be on the remote device. Deleting on the remote device is currently not supported.

**Comment by napseis** [comment]
hi, 
Not sure I selected the relevant part below, when adding with QR code. I noticed that it crashes as well in the following case:
- click add manual remote id
- press go back without entering anything

`
FATAL EXCEPTION: main
Process: net.syncthing.lite, PID: 14625
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.syncthing.lite/net.syncthing.lite.activities.MainActivity}: kotlin.KotlinNullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4571)
at android.app.ActivityThread.-wrap19(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1513)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6236)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: kotlin.KotlinNullPointerException
at net.syncthing.lite.activities.SyncthingActivity.syncthingClient(SyncthingActivity.kt:33)
at net.syncthing.lite.fragments.DevicesFragment.updateDeviceList(DevicesFragment.kt:74)
at net.syncthing.lite.fragments.DevicesFragment.onActivityCreated(DevicesFragment.kt:52)
at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2270)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
at android.app.Activity.performStart(Activity.java:6701)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2662)
... 10 more
[ 12-31 11:18:32.085 17591:13572 W/ActivityManager ]
  Force finishing activity net.syncthing.lite/.activities.MainActivity
[ 12-31 11:18:32.093 17591:13572 W/ContextImpl ]
Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:877 com.android.server.am.AppErrors.crashApplicationInner:375 com.android.server.am.AppErrors.crashApplication:309 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:13754 com.android.server.am.ActivityManagerService.handleApplicationCrash:13736 
[ 12-31 11:18:32.124 17591:18982 I/WindowManager ]
Screen frozen for +221ms due to AppWindowToken{43934a5 token=Token{def420f ActivityRecord{c577b6e u0 net.syncthing.lite/.activities.MainActivity t893}}}
[ 12-31 11:18:32.133 14625:14819 I/LibConnectionHandler ]
loaded mConfiguration = #Sun Dec 31 11:18:32 GMT+01:00 2017
cache=/storage/emulated/0/Android/data/net.syncthing.lite/cache/cache
database=/storage/emulated/0/Android/data/net.syncthing.lite/files/database
`
